# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7834dfeb6cc19667a7def20ca81235dc88a02e6788e1a1712cdb881e4d7bead5d7bccc1959330b6d87fa71a9c87d64af0b8ef1d43f865ab81edbe81fdf40e37b

test:
  secret_key_base: 1a2c2ba2b82228976090455cfc34cedf189bbd8f662fe33f19b9da54e66662df1a42858bd74a51b79696ea9791cad65db2b69e60ebf34adc70d90f1da35feb0e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
